language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: YRLWhWgjVm4z9ckwnaTuxCTEECwVkDEFkV5Qwn52z2vUBuFkEZvulTjKHQEU52uEMIr6bD9Adn0uPNa18kKN9gKfMZbsDweBHR/xqKMtWTF2AZsZBX0udhu30Om+7h4H78Vw2zOPjOVdzTB7rO3zVHDmAI17TTdpKJBFc6KglKJ6psPc0BI3P5uMWxQaB6UDqfBO5dsGnrdEPhh1a200hzrxeV/SYx6YI2uksftaBw0nKcBc3U592ZFSjYU2SUgpti0CnXfOZ8Z8/YxD1dJM6XBtEbiUO3HIwrlKUJrwDupCCwr03n6pQtMt7CIrxYMoaF2/jo60cWNaHyo3qaUCOy98XOl8kUfVR872ds5mYMTr66p69L/xlO6HtEOhiMQ7Dm6XHF495uesc1knVsNt3L+ByQs45H0sY68fP6sVu8ZC/A4W5YMoVJeD3pHciHy+WEDfEOaufHuzGfBgSCqNR9OeDm1rEeUc0XikAGp2ZxheTw+rzoXZUaXNgWPI53JkkH7unfIC/tdx8UskBsj+IpjI1XSRjm13CNz6ljozDXiOx7mKh3wZlgd0ngDqDsXqxGENoih/wlmMIKvJe3CS9go3taOcAw1LctKqcJIrR1GBDfmVoBIETaVQkBYMeXzy4/3hinRF3jrBhr2dcexEW5LQkcI+Fer1omUtG72RatI=
  app: wishlist-capstone
  on:
    repo: J-Vega/wishlist-app-api
